import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/header/Header";
import { Providers } from "../providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stopwatch",
  description: "Generated by create next app",
};

export default function StopwatchLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="" suppressHydrationWarning>
      <head></head>
      <body className={`${inter.className}`}>
        <Providers>
          <div className="container-2xl grid grid-rows-auto1fr grid-cols-full min-h-screen">
            <main className="">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
