import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="container-2xl grid grid-rows-auto1fr grid-cols-full min-h-screen">
          <header className="bg-red-500 dark:bg-red-400 p-2">
            <Header />
          </header>
          <main className="">{children}</main>
          <footer className="bg-red-950 text-center text-white dark:bg-red-200 dark:text-black p-1">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
